# -*- coding: utf-8 -*-
"""Graph Rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ps5De94_8VkQOyDu9nQfIrWVcbTk9YTn
"""

!pip install faiss-cpu
import faiss
import numpy as np
import torch
import networkx as nx
from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline
from sklearn.metrics.pairwise import cosine_similarity

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('pritamdeka/S-BioBert-snli-multinli-stsb')

tokenizer = AutoTokenizer.from_pretrained('pritamdeka/S-BioBert-snli-multinli-stsb')
model = AutoModelForTokenClassification.from_pretrained('pritamdeka/S-BioBert-snli-multinli-stsb')
ner_pipeline = pipeline("ner", model=model, tokenizer=tokenizer, grouped_entities=True)

def embed_query(query, embed_model):
    return embed_model.encode([query])[0]

def cosine_top_k(query_vec, doc_vecs, k=5):
    similarities = cosine_similarity([query_vec], doc_vecs)[0]
    top_k_idx = np.argsort(similarities)[::-1][:k]
    return top_k_idx, similarities[top_k_idx]

def extract_entities(text):
    results = ner_pipeline(text)
    return list(set([r['word'] for r in results]))

def retrieve_docs_from_multiqueries(queries, embed_model, faiss_index, all_doc_embeddings, metadata, top_k=5):
    all_retrieved_texts = []
    all_entities = set()

    for q in queries:
        q_vec = embed_query(q, embed_model)

        q_vec = q_vec / np.linalg.norm(q_vec)
        D, I = faiss_index.search(np.array([q_vec]), top_k)

        for idx in I[0]:
            doc_text = metadata[idx]
            all_retrieved_texts.append(doc_text)
            entities = extract_entities(doc_text)
            all_entities.update(entities)

    return all_retrieved_texts, list(all_entities)

def build_knowledge_subgraph(entities, triples):
    G = nx.DiGraph()

    for head, rel, tail in triples:
        if head in entities or tail in entities:
            G.add_edge(head, tail, relation=rel)

    return G



