# -*- coding: utf-8 -*-
"""VectorDB_Sim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2J5k_k63NTJa2qU0EaYR8PGn3yGiWd1
"""

!pip install faiss-cpu transformers scikit-learn


import numpy as np
import faiss
import torch
import json
from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline
from sklearn.metrics.pairwise import cosine_similarity
import networkx as nx
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('pritamdeka/S-BioBert-snli-multinli-stsb')

# JSON chunks
with open("chunks_with_entities.json", "r") as f:
    chunks = json.load(f)

texts = [c["text"] for c in chunks]
embeddings = np.array([c["embedding"] for c in chunks]).astype("float32")
metadata_dict = {i: c["metadata"] for i, c in enumerate(chunks)}

multi_queries = "How does point-of-care procalcitonin (PCT) testing influence the timeliness and effectiveness of antibiotic administration in emergency department patients with suspected sepsis compared to central lab PCT testing?"  # replace with real multi-queries

# FAISS index
index = faiss.read_index("chunks.index")
faiss.normalize_L2(embeddings)

query_vector = model.encode(multi_queries, convert_to_tensor=True).numpy()
query_vector = query_vector.reshape(1,-1)
faiss.normalize_L2(query_vector)

distances, indexes = index.search(query_vector, 10)
index.add(embeddings)
print(distances, indexes)

tokenizer = AutoTokenizer.from_pretrained('pritamdeka/S-BioBert-snli-multinli-stsb')
model = AutoModelForTokenClassification.from_pretrained('pritamdeka/S-BioBert-snli-multinli-stsb')
ner = pipeline("ner", model=model, tokenizer=tokenizer, grouped_entities=True)

def extract_entities(text):
    return list(set([ent["word"] for ent in ner(text)]))

def graph_rag_retrieval(multi_queries, embed_func, faiss_index, metadata_dict, texts, kg_triples, top_k=5):
    retrieved_texts = []
    entity_set = set()

    for q in multi_queries:
        q_vec = embed_func(q)
        q_vec = q_vec / np.linalg.norm(q_vec)
        D, I = faiss_index.search(np.array([q_vec], dtype="float32"), top_k)
        for idx in I[0]:
            text = texts[idx]
            retrieved_texts.append(text)
            entity_set.update(extract_entities(text))

    # Build KG Subgraph
    G = nx.DiGraph()
    for h, r, t in kg_triples:
        if h in entity_set or t in entity_set:
            G.add_edge(h, t, relation=r)

    return retrieved_texts, list(G.edges(data=True))

from sentence_transformers import SentenceTransformer
model_embed = SentenceTransformer("bert-base-nli-mean-tokens")

def embed_func(text):
    return model_embed.encode(text, normalize_embeddings=True)

multi_queries = "How does point-of-care procalcitonin (PCT) testing influence the timeliness and effectiveness of antibiotic administration in emergency department patients with suspected sepsis compared to central lab PCT testing?"  # replace with real multi-queries
kg_triples = [("COVID", "related_to", "vaccine"), ("RNA", "encodes", "protein")]  # example

retrieved_docs, subgraph_edges = graph_rag_retrieval(
    multi_queries=multi_queries,
    embed_func=embed_func,
    faiss_index=index,
    metadata_dict=metadata_dict,
    texts=texts,
    kg_triples=kg_triples,
    top_k=5
)

print("\n🔍 Top Retrieved Chunks:\n")
for i, text in enumerate(retrieved_docs):
    print(f"Chunk {i+1}:\n{text[:500]}...\n")
    print(f"Metadata: {metadata_dict[i]}\n{'-'*60}")

print("\n🧠 Knowledge Graph Subgraph Edges:\n")
for (h, t, r) in subgraph_edges:
    print(f"{h} --[{r['relation']}]--> {t}")